export const Icons = {
  download: '/icons/download.svg',
  close: '/icons/close.png',
  menu: '/icons/menu.png',
  arrowRight: '/icons/arrow-right.svg',
  share: '/icons/share.png',
  android: '/icons/android.png',
  ios: '/icons/ios.png',
  web: '/icons/web.png',
  react: '/icons/react.png',
  reactNative: '/icons/react-native.png',
  rust: '/icons/rust.png',
  golang: '/icons/golang.png',
  nodejs: '/icons/nodejs.png',
  github: '/icons/github.png',
  javascript: '/icons/javascript.png',
};
